[colors.primary]
background = '#261d18'
foreground = '#f3f2f2'
 
[colors.cursor]
text = '#f3f2f2'
cursor = '#b6b2af' 
 
[colors.vi_mode_cursor]
text = '#261d18'
cursor = '#e49767' 
 
[colors.search.matches]
foreground = '#32271f' 
background = '#a5cc66' 
 
[colors.search.focused_match]
foreground = '#32271f' 
background = '#e49767' 
 
[colors.footer_bar]
foreground = '#32271f' 
background = '#e8e5e3' 
 
[colors.hints.start]
foreground = '#32271f' 
background = '#d6c85c' 
 
[colors.hints.end]
foreground = '#32271f' 
background = '#d6c85c' 
 
[colors.selection]
text = '#261d18'
background = '#e49767'
 
 
[colors.normal]
black = '#181818' 
red = '#fd4663' 
green = '#e49767' 
yellow = '#995a33' 
blue = '#e49767' 
magenta = '#a5cc66' 
cyan = '#d6c85c' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 