[font]
size = 11.0

[font.normal]
family = "LMMono10"
style = "Regular"

[colors.primary]
background = '#292214'
foreground = '#f3f2f2'
 
[colors.cursor]
text = '#f3f2f2'
cursor = '#b6b4af' 
 
[colors.vi_mode_cursor]
text = '#292214'
cursor = '#e7bb64' 
 
[colors.search.matches]
foreground = '#372d1b' 
background = '#81e44e' 
 
[colors.search.focused_match]
foreground = '#372d1b' 
background = '#e7bb64' 
 
[colors.footer_bar]
foreground = '#372d1b' 
background = '#e8e6e3' 
 
[colors.hints.start]
foreground = '#372d1b' 
background = '#cce44e' 
 
[colors.hints.end]
foreground = '#372d1b' 
background = '#cce44e' 
 
[colors.selection]
text = '#292214'
background = '#e7bb64'
 
 
[colors.normal]
black = '#181818' 
red = '#fd4663' 
green = '#e7bb64' 
yellow = '#a2792a' 
blue = '#e7bb64' 
magenta = '#81e44e' 
cyan = '#cce44e' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 