# hyprlock.conf - Omarchy exact layout synced with Noctalia theme

$color = rgb(261d18)
$inner_color = rgba(3f3027dd)
$outer_color = rgb(e49767)
$font_color = rgb(f3f2f2)
$check_color = rgb(a5cc66)
$topbar_color = rgba(261d18ff)

## General configs
general {
    ignore_empty_input = true
    hide_cursor = true
}

auth {
    fingerprint:enabled = false
}

## Silky-smooth animations
animations {
    enabled = true
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = easeInExpo, 0.7, 0, 0.84, 0
    animation = fadeIn, 1, 6, easeOutExpo
    animation = fadeOut, 1, 4, easeInExpo
    animation = inputFieldDots, 1, 4, easeOutExpo
}

## Wallpaper
background {
    monitor =
    color = $color
    path = screenshot
    blur_passes = 5
}

## Password field
input-field {
    monitor =
    size = 550, 55
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4
    dots_size = 0.24
    dots_spacing = 0.24

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = <span size="smaller" alpha="50%">Enter Password</span>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

## Top bar
shape {
    size = 100%, 52
    position = 0, 0
    halign = center
    valign = top
    color = $topbar_color
    border_size = 0
    rounding = 0
}

## Clock
label {
    text = $TIME
    font_size = 18
    halign = center
    valign = top
    position = 0, 12
    font_family = JetBrainsMono Nerd Font Propo
    color = $font_color
}

## Right portion of top bar
label {
    text = cmd[update:2000] hyprlock-bar-right
    font_size = 14
    text_align = right
    halign = right
    valign = top
    position = -25, 14
    font_family = JetBrainsMono Nerd Font Propo
    color = $font_color
}

## System info line
label {
    text = cmd[update:3600000] hyprlock-system-info
    font_size = 13
    halign = center
    valign = bottom
    position = 0, 50
    font_family = JetBrainsMono Nerd Font
    color = $font_color
}

## KVM label
label {
    text = cmd[update:2000] bash -c 'grep -q "Name=\"CX 2.4G Wireless Receiver Keyboard\"" /proc/bus/input/devices && echo "KVM"'
    font_size = 13
    halign = center
    valign = center
    position = 380, 0
    font_family = JetBrainsMono Nerd Font
    color = $font_color
}

## Bindings
label {
    text = <span weight="bold" alpha="72%">[Super+Esc]</span> <span alpha="56%">Display off</span>   <span weight="bold" alpha="72%">[Super+S]</span> <span alpha="56%">Suspend</span>   <span weight="bold" alpha="72%">[Super+R]</span> <span alpha="56%">Reboot</span>   <span weight="bold" alpha="72%">[Super+P]</span> <span alpha="56%">Power off</span>
    font_size = 13
    halign = center
    valign = bottom
    position = 0, 20
    font_family = JetBrainsMono Nerd Font
    color = $font_color
}
