foreground            #e8e1dd
background            #151311
selection_foreground  #3d2e18
selection_background  #dbc3a3
url_color             #bdc7da
cursor                #dbc3a3
cursor_text_color     #3d2e18

color0   #151311
color1   #ffb4ab
color2   #dbc3a3
color3   #bdc7da
color4   #dbc3a3
color5   #bdc7da
color6   #3d4757
color7   #e8e1dd

color8   #998f84
color9   #ffb4ab
color10  #dbc3a3
color11  #bdc7da
color12  #dbc3a3
color13  #bdc7da
color14  #3d4757
color15  #e8e1dd

tab_bar_background              #151311
tab_bar_margin_color            #151311
active_tab_foreground           #3d2e18
active_tab_background           #dbc3a3
inactive_tab_foreground         #d0c5b9
inactive_tab_background         #151311
